import random
from faker import Faker
fake = Faker()


def generate_random_pr_data():

    username = fake.user_name()
    repo_name = fake.user_name()
    owner_name = fake.user_name()

    label_count = fake.pyint(0, 10)
    assignee_count = fake.pyint(0, 10)
    reviewer_count = fake.pyint(0, 10)

    {"url": f"https://api.github.com/repos/{owner_name}/{repo_name}/pulls/1",
     "id": 514856678, "node_id": "MDExOlB1bGxSZXF1ZXN0NTE0ODU2Njc4",
     "html_url": "https://github.com/{owner_name}/{repo_name}/pull/1",
     "diff_url": "https://github.com/{owner_name}/{repo_name}/pull/1.diff",
     "patch_url": "https://github.com/{owner_name}/{repo_name}/pull/1.patch",
     "issue_url": "https://api.github.com/repos/{owner_name}/{repo_name}/issues/1",
     "number": 1, "state": "closed",
     "locked": False, "title": "add Architectural Decision Record",
     "user": {
            "login": username,
            "id": 260331, "node_id": "MDQ6VXNlcjI2MDMzMQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/260331?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/{username}",
            "html_url": "https://github.com/{username}",
            "followers_url": "https://api.github.com/users/{username}/followers",
            "following_url": "https://api.github.com/users/{username}/following{/other_user}",
            "gists_url": "https://api.github.com/users/{username}/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/{username}/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/{username}/subscriptions",
            "organizations_url": "https://api.github.com/users/{username}/orgs",
            "repos_url": "https://api.github.com/users/{username}/repos",
            "events_url": "https://api.github.com/users/{username}/events{/privacy}",
            "received_events_url": "https://api.github.com/users/{username}/received_events",
            "type": "User",
     "site_admin": False}, "body": "add ADR documentation to keep track of architectural decisions\r\n\r\nSigned-off-by: Christoph Gö ZWwyNDc3NTQ2MzE2",
     "url": "https://api.github.com/repos/{owner_name}/{repo_name}/labels/approved",
     "name": "approved",
     "color": "0e8a16",
     "default": False, "description": "Indicates a PR has been approved by an approver from all required OWNERS files."}], 
     "milestone": None, "draft": False, "commits_url": "https://api.github.com/repos/{owner_name}/{repo_name}/pulls/1/commits",
     "review_comments_url": "https://api.github.com/repos/{owner_name}/{repo_name}/pulls/1/comments",
     "review_comment_url": "https://api.github.com/repos/{owner_name}/{repo_name}/pulls/comments{/number}",
     "comments_url": "https://api.github.com/repos/{owner_name}/{repo_name}/issues/1/comments",
     "statuses_url": "https://api.github.com/repos/{owner_name}/{repo_name}/statuses/9e7e4295a7e679b06d90d7bfdc0e9c87d0cc6e0d",
     "head": {"label": f"{username}:main",
     "ref": "main",
     "sha": "9e7e4295a7e679b06d90d7bfdc0e9c87d0cc6e0d",
     "user": {"login": username,
     "id": 260331, "node_id": "MDQ6VXNlcjI2MDMzMQ==",
     "avatar_url": "https://avatars.githubusercontent.com/u/260331?v=4",
     "gravatar_id": "",
     "url": "https://api.github.com/users/{username}",
     "html_url": "https://github.com/{username}",
     "followers_url": "https://api.github.com/users/{username}/followers",
     "following_url": "https://api.github.com/users/{username}/following{/other_user}",
     "gists_url": "https://api.github.com/users/{username}/gists{/gist_id}",
     "starred_url": "https://api.github.com/users/{username}/starred{/owner}{/repo}",
     "subscriptions_url": "https://api.github.com/users/{username}/subscriptions",
     "organizations_url": "https://api.github.com/users/{username}/orgs",
     "repos_url": "https://api.github.com/users/{username}/repos",
     "events_url": "https://api.github.com/users/{username}/events{/privacy}",
     "received_events_url": "https://api.github.com/users/{username}/received_events",
     "type": "User",
     "site_admin": False}, "repo": {"id": 309662608, "node_id": "MDEwOlJlcG9zaXRvcnkzMDk2NjI2MDg=",
     "name": f"{owner_name}-{repo_name}",
     "full_-blueprint/git/tags{/sha}",
     "git_refs_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/git/refs{/sha}",
     "trees_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/git/trees{/sha}",
     "statuses_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/statuses/{sha}",
     "languages_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/languages",
     "stargazers_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/stargazers",
     "contributors_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/contributors",
     "subscribers_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/subscribers",
     "subscription_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/subscription",
     "commits_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/commits{/sha}",
     "git_commits_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/git/commits{/sha}",
     "comments_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/comments{/number}",
     "issue_comment_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/issues/comments{/number}",
     "contents_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/contents/{+path}",
     "compare_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/compare/{base}...{head}",
     "merges_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/merges",
     "archive_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/{archive_format}{/ref}",
     "downloads_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/downloads",
     "issues_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/issues{/number}",
     "pulls_url": "https://api.github.com/repos/{username}/{owner_name}-{repo_name}/pulls{/number}",
     "milestones_url": "https://api.git{/repo}",
     "subscriptions_url": "https://api.github.com/users/{owner_name}/subscriptions",
     "organizations_url": "https://api.github.com/users/{owner_name}/orgs",
     "repos_url": "https://api.github.com/users/{owner_name}/repos",
     "events_url": "https://api.github.com/users/{owner_name}/events{/privacy}",
     "received_events_url": "https://api.github.com/users/{owner_name}/received_events",
     "type": "Organization",
     "site_admin": False}, "repo": {"id": 309661776, "node_id": "MDEwOlJlcG9zaXRvcnkzMDk2NjE3NzY=",
     "name": {repo_name},
     "full_name": "{owner_name}/{repo_name}",
     "private": False, "owner": {"login": owner_name,
     "id": 70260562, "node_id": "MDEyOk9yZ2FuaXphdGlvbjcwMjYwNTYy",
     "avatar_url": "https://avatars.githubusercontent.com/u/70260562?v=4",
     "gravatar_id": "",
     "url": "https://api.github.com/users/{owner_name}",
     "html_url": "https://github.com/{owner_name}",
     "followers_url": "https://api.github.com/users/{owner_name}/followers",
     "following_url": "https://api.github.com/users/{owner_name}/following{/other_user}",
     "gists_url": "https://api.github.com/users/{owner_name}/gists{/gist_id}",
     "starred_url": "https://api.github.com/users/{owner_name}/starred{/owner}{/repo}",
     "subscriptions_url": "https://api.github.com/users/{owner_name}/subscriptions",
     "organizations_url": "https://api.github.com/users/{owner_name}/orgs",
     "repos_url": "https://api.github.com/users/{owner_name}/repos",
     "events_url": "https://api.github.com/users/{owner_name}/events{/privacy}",
     "received_events_url": "https://api.github.com/users/{owner_name}/received_events",
     "type": "Organization",
     "site_admin": False}, "html_url": "https://github.com/{owner_name}/{repo_name}",
     "description": "This is the blueprint for the Operate First Initiative",
     "fork": False, "url": "https://api.github.com/repos/{owner_name}/{repo_name}",
     "forks_url": "https://api.githu.{head}",
     "merges_url": "https://api.github.com/repos/{owner_name}/{repo_name}/merges",
     "archive_url": "https://api.github.com/repos/{owner_name}/{repo_name}/{archive_format}{/ref}",
     "downloads_url": "https://api.github.com/repos/{owner_name}/{repo_name}/downloads",
     "issues_url": "https://api.github.com/repos/{owner_name}/{repo_name}/issues{/number}",
     "pulls_url": "https://api.github.com/repos/{owner_name}/{repo_name}/pulls{/number}",
     "milestones_url": "https://api.github.com/repos/{owner_name}/{repo_name}/milestones{/number}",
     "notifications_url": "https://api.github.com/repos/{owner_name}/{repo_name}/notifications{?since,all,participating}",
     "labels_url": "https://api.github.com/repos/{owner_name}/{repo_name}/labels{/name}",
     "releases_url": "https://api.github.com/repos/{owner_name}/{repo_name}/releases{/id}",
     "deployments_url": "https://api.github.com/repos/{owner_name}/{repo_name}/deployments",
     "created_at": "2020-11-03T11:15:31Z",
     "updated_at": "2022-06-28T10:54:26Z",
     "pushed_at": "2022-11-09T17:06:12Z",
     "git_url": "git://github.com/{owner_name}/{repo_name}.git",
     "ssh_url": "git@github.com:operate-first/{repo_name}.git",
     "clone_url": "https://github.com/{owner_name}/{repo_name}.git",
     "svn_url": "https://github.com/{owner_name}/{repo_name}",
     "homepage": "",
     "size": 1837, "stargazers_count": 8, "watchers_count": 8, "language": None, "has_issues": True, "has_projects": False, "has_downloads": True, "has_wiki": False, "has_pages": True, "has_discussions": False, "forks_count": 16, "mirror_url": None, "archived": False, "disabled": False, "open_issues_count": 1, "license": {"key": "gpl-3.0",
     "name": "GNU General Public License v3.0",
     "spdx_id": "GPL-3.0",
     "url": "https://api.github.com/licenses/gpl-3.0",
     "node_id": "MDc6TGljZW5zZTk="}, "allow_forking": True, "is_template": False, "web_commit_signoff_required": False, "topics": ["architectural-decisions",
     "bluues/1"}, "comments": {"href": "https://api.github.com/repos/{owner_name}/{repo_name}/issues/1/comments"}, "review_comments": {"href": "https://api.github.com/repos/{owner_name}/{repo_name}/pulls/1/comments"}, "review_comment": {"href": "https://api.github.com/repos/{owner_name}/{repo_name}/pulls/comments{/number}"}, "commits": {"href": "https://api.github.com/repos/{owner_name}/{repo_name}/pulls/1/commits"}, "statuses": {"href": "https://api.github.com/repos/{owner_name}/{repo_name}/statuses/9e7e4295a7e679b06d90d7bfdc0e9c87d0cc6e0d"}}, "author_association": "MEMBER",
     "auto_merge": None, "active_lock_reason": None, "merged": True, "mergeable": None, "rebaseable": None, "mergeable_state": "unknown",
     "merged_by": {"login": "sesheta",
     "id": 33906690, "node_id": "MDQ6VXNlcjMzOTA2Njkw",
     "avatar_url": "https://avatars.githubusercontent.com/u/33906690?v=4",
     "gravatar_id": "",
     "url": "https://api.github.com/users/sesheta",
     "html_url": "https://github.com/sesheta",
     "followers_url": "https://api.github.com/users/sesheta/followers",
     "following_url": "https://api.github.com/users/sesheta/following{/other_user}",
     "gists_url": "https://api.github.com/users/sesheta/gists{/gist_id}",
     "starred_url": "https://api.github.com/users/sesheta/starred{/owner}{/repo}",
     "subscriptions_url": "https://api.github.com/users/sesheta/subscriptions",
     "organizations_url": "https://api.github.com/users/sesheta/orgs",
     "repos_url": "https://api.github.com/users/sesheta/repos",
     "events_url": "https://api.github.com/users/sesheta/events{/privacy}",
     "received_events_url": "https://api.github.com/users/sesheta/received_events",
     "type": "User",
     "site_admin": False}, "comments": 1, "review_comments": 4, "maintainer_can_modify": False, "commits": 2, "additions": 136, "deletions": 2, "changed_files": 4}