issue_data = [
    {
        "url": "https://api.github.com/repos/ABrain7710/augur_test/issues/5",
        "repository_url": "https://api.github.com/repos/ABrain7710/augur_test",
        "labels_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/5/labels{/name}",
        "comments_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/5/comments",
        "events_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/5/events",
        "html_url": "https://github.com/ABrain7710/augur_test/issues/5",
        "id": 1570682249,
        "node_id": "I_kwDOI5lKg85dnrWJ",
        "number": 5,
        "title": "Closed issue",
        "user": {
            "login": "ABrain7710",
            "id": 61482022,
            "node_id": "MDQ6VXNlcjYxNDgyMDIy",
            "avatar_url": "https://avatars.githubusercontent.com/u/61482022?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ABrain7710",
            "html_url": "https://github.com/ABrain7710",
            "followers_url": "https://api.github.com/users/ABrain7710/followers",
            "following_url": "https://api.github.com/users/ABrain7710/following{/other_user}",
            "gists_url": "https://api.github.com/users/ABrain7710/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ABrain7710/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ABrain7710/subscriptions",
            "organizations_url": "https://api.github.com/users/ABrain7710/orgs",
            "repos_url": "https://api.github.com/users/ABrain7710/repos",
            "events_url": "https://api.github.com/users/ABrain7710/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ABrain7710/received_events",
            "type": "User",
            "site_admin": False
        },
        "labels": [],
        "state": "closed",
        "locked": False,
        "assignee": None,
        "assignees": [],
        "milestone": None,
        "comments": 0,
        "created_at": "2023-02-04T01:05:11Z",
        "updated_at": "2023-02-04T01:05:18Z",
        "closed_at": "2023-02-04T01:05:18Z",
        "author_association": "OWNER",
        "active_lock_reason": None,
        "body": None,
        "reactions": {
            "url": "https://api.github.com/repos/ABrain7710/augur_test/issues/5/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/5/timeline",
        "performed_via_github_app": None,
        "state_reason": "completed"
    },
    {
        "url": "https://api.github.com/repos/ABrain7710/augur_test/issues/4",
        "repository_url": "https://api.github.com/repos/ABrain7710/augur_test",
        "labels_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/4/labels{/name}",
        "comments_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/4/comments",
        "events_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/4/events",
        "html_url": "https://github.com/ABrain7710/augur_test/issues/4",
        "id": 1570681775,
        "node_id": "I_kwDOI5lKg85dnrOv",
        "number": 4,
        "title": "Issue with Description",
        "user": {
            "login": "ABrain7710",
            "id": 61482022,
            "node_id": "MDQ6VXNlcjYxNDgyMDIy",
            "avatar_url": "https://avatars.githubusercontent.com/u/61482022?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ABrain7710",
            "html_url": "https://github.com/ABrain7710",
            "followers_url": "https://api.github.com/users/ABrain7710/followers",
            "following_url": "https://api.github.com/users/ABrain7710/following{/other_user}",
            "gists_url": "https://api.github.com/users/ABrain7710/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ABrain7710/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ABrain7710/subscriptions",
            "organizations_url": "https://api.github.com/users/ABrain7710/orgs",
            "repos_url": "https://api.github.com/users/ABrain7710/repos",
            "events_url": "https://api.github.com/users/ABrain7710/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ABrain7710/received_events",
            "type": "User",
            "site_admin": False
        },
        "labels": [],
        "state": "open",
        "locked": False,
        "assignee": None,
        "assignees": [],
        "milestone": None,
        "comments": 0,
        "created_at": "2023-02-04T01:04:10Z",
        "updated_at": "2023-02-04T01:04:10Z",
        "closed_at": None,
        "author_association": "OWNER",
        "active_lock_reason": None,
        "body": "Issue description...",
        "reactions": {
            "url": "https://api.github.com/repos/ABrain7710/augur_test/issues/4/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/4/timeline",
        "performed_via_github_app": None,
        "state_reason": None
    },
    {
        "url": "https://api.github.com/repos/ABrain7710/augur_test/issues/3",
        "repository_url": "https://api.github.com/repos/ABrain7710/augur_test",
        "labels_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/3/labels{/name}",
        "comments_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/3/comments",
        "events_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/3/events",
        "html_url": "https://github.com/ABrain7710/augur_test/issues/3",
        "id": 1570676213,
        "node_id": "I_kwDOI5lKg85dnp31",
        "number": 3,
        "title": "Issue with Labels",
        "user": {
            "login": "ABrain7710",
            "id": 61482022,
            "node_id": "MDQ6VXNlcjYxNDgyMDIy",
            "avatar_url": "https://avatars.githubusercontent.com/u/61482022?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ABrain7710",
            "html_url": "https://github.com/ABrain7710",
            "followers_url": "https://api.github.com/users/ABrain7710/followers",
            "following_url": "https://api.github.com/users/ABrain7710/following{/other_user}",
            "gists_url": "https://api.github.com/users/ABrain7710/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ABrain7710/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ABrain7710/subscriptions",
            "organizations_url": "https://api.github.com/users/ABrain7710/orgs",
            "repos_url": "https://api.github.com/users/ABrain7710/repos",
            "events_url": "https://api.github.com/users/ABrain7710/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ABrain7710/received_events",
            "type": "User",
            "site_admin": False
        },
        "labels": [
            {
                "id": 5114228621,
                "node_id": "LA_kwDOI5lKg88AAAABMNTvjQ",
                "url": "https://api.github.com/repos/ABrain7710/augur_test/labels/bug",
                "name": "bug",
                "color": "d73a4a",
                "default": True,
                "description": "Something isn't working"
            },
            {
                "id": 5114228632,
                "node_id": "LA_kwDOI5lKg88AAAABMNTvmA",
                "url": "https://api.github.com/repos/ABrain7710/augur_test/labels/help%20wanted",
                "name": "help wanted",
                "color": "008672",
                "default": True,
                "description": "Extra attention is needed"
            }
        ],
        "state": "open",
        "locked": False,
        "assignee": None,
        "assignees": [],
        "milestone": None,
        "comments": 0,
        "created_at": "2023-02-04T00:54:24Z",
        "updated_at": "2023-02-04T00:54:24Z",
        "closed_at": None,
        "author_association": "OWNER",
        "active_lock_reason": None,
        "body": None,
        "reactions": {
            "url": "https://api.github.com/repos/ABrain7710/augur_test/issues/3/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/3/timeline",
        "performed_via_github_app": None,
        "state_reason": None
    },
    {
        "url": "https://api.github.com/repos/ABrain7710/augur_test/issues/2",
        "repository_url": "https://api.github.com/repos/ABrain7710/augur_test",
        "labels_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/2/labels{/name}",
        "comments_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/2/comments",
        "events_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/2/events",
        "html_url": "https://github.com/ABrain7710/augur_test/issues/2",
        "id": 1570676070,
        "node_id": "I_kwDOI5lKg85dnp1m",
        "number": 2,
        "title": "Issue with Assignee",
        "user": {
            "login": "ABrain7710",
            "id": 61482022,
            "node_id": "MDQ6VXNlcjYxNDgyMDIy",
            "avatar_url": "https://avatars.githubusercontent.com/u/61482022?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ABrain7710",
            "html_url": "https://github.com/ABrain7710",
            "followers_url": "https://api.github.com/users/ABrain7710/followers",
            "following_url": "https://api.github.com/users/ABrain7710/following{/other_user}",
            "gists_url": "https://api.github.com/users/ABrain7710/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ABrain7710/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ABrain7710/subscriptions",
            "organizations_url": "https://api.github.com/users/ABrain7710/orgs",
            "repos_url": "https://api.github.com/users/ABrain7710/repos",
            "events_url": "https://api.github.com/users/ABrain7710/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ABrain7710/received_events",
            "type": "User",
            "site_admin": False
        },
        "labels": [],
        "state": "open",
        "locked": False,
        "assignee": {
            "login": "ABrain7710",
            "id": 61482022,
            "node_id": "MDQ6VXNlcjYxNDgyMDIy",
            "avatar_url": "https://avatars.githubusercontent.com/u/61482022?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ABrain7710",
            "html_url": "https://github.com/ABrain7710",
            "followers_url": "https://api.github.com/users/ABrain7710/followers",
            "following_url": "https://api.github.com/users/ABrain7710/following{/other_user}",
            "gists_url": "https://api.github.com/users/ABrain7710/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ABrain7710/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ABrain7710/subscriptions",
            "organizations_url": "https://api.github.com/users/ABrain7710/orgs",
            "repos_url": "https://api.github.com/users/ABrain7710/repos",
            "events_url": "https://api.github.com/users/ABrain7710/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ABrain7710/received_events",
            "type": "User",
            "site_admin": False
        },
        "assignees": [
            {
                "login": "ABrain7710",
                "id": 61482022,
                "node_id": "MDQ6VXNlcjYxNDgyMDIy",
                "avatar_url": "https://avatars.githubusercontent.com/u/61482022?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ABrain7710",
                "html_url": "https://github.com/ABrain7710",
                "followers_url": "https://api.github.com/users/ABrain7710/followers",
                "following_url": "https://api.github.com/users/ABrain7710/following{/other_user}",
                "gists_url": "https://api.github.com/users/ABrain7710/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ABrain7710/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ABrain7710/subscriptions",
                "organizations_url": "https://api.github.com/users/ABrain7710/orgs",
                "repos_url": "https://api.github.com/users/ABrain7710/repos",
                "events_url": "https://api.github.com/users/ABrain7710/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ABrain7710/received_events",
                "type": "User",
                "site_admin": False
            }
        ],
        "milestone": None,
        "comments": 0,
        "created_at": "2023-02-04T00:54:05Z",
        "updated_at": "2023-02-04T00:54:06Z",
        "closed_at": None,
        "author_association": "OWNER",
        "active_lock_reason": None,
        "body": None,
        "reactions": {
            "url": "https://api.github.com/repos/ABrain7710/augur_test/issues/2/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/2/timeline",
        "performed_via_github_app": None,
        "state_reason": None
    },
    {
        "url": "https://api.github.com/repos/ABrain7710/augur_test/issues/1",
        "repository_url": "https://api.github.com/repos/ABrain7710/augur_test",
        "labels_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/1/labels{/name}",
        "comments_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/1/comments",
        "events_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/1/events",
        "html_url": "https://github.com/ABrain7710/augur_test/issues/1",
        "id": 1570675895,
        "node_id": "I_kwDOI5lKg85dnpy3",
        "number": 1,
        "title": "Empty Issue",
        "user": {
            "login": "ABrain7710",
            "id": 61482022,
            "node_id": "MDQ6VXNlcjYxNDgyMDIy",
            "avatar_url": "https://avatars.githubusercontent.com/u/61482022?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ABrain7710",
            "html_url": "https://github.com/ABrain7710",
            "followers_url": "https://api.github.com/users/ABrain7710/followers",
            "following_url": "https://api.github.com/users/ABrain7710/following{/other_user}",
            "gists_url": "https://api.github.com/users/ABrain7710/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ABrain7710/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ABrain7710/subscriptions",
            "organizations_url": "https://api.github.com/users/ABrain7710/orgs",
            "repos_url": "https://api.github.com/users/ABrain7710/repos",
            "events_url": "https://api.github.com/users/ABrain7710/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ABrain7710/received_events",
            "type": "User",
            "site_admin": False
        },
        "labels": [],
        "state": "open",
        "locked": False,
        "assignee": None,
        "assignees": [],
        "milestone": None,
        "comments": 0,
        "created_at": "2023-02-04T00:53:43Z",
        "updated_at": "2023-02-04T00:53:43Z",
        "closed_at": None,
        "author_association": "OWNER",
        "active_lock_reason": None,
        "body": None,
        "reactions": {
            "url": "https://api.github.com/repos/ABrain7710/augur_test/issues/1/reactions",
            "total_count": 0,
            "+1": 0,
            "-1": 0,
            "laugh": 0,
            "hooray": 0,
            "confused": 0,
            "heart": 0,
            "rocket": 0,
            "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/ABrain7710/augur_test/issues/1/timeline",
        "performed_via_github_app": None,
        "state_reason": None
    }
]

def get_random_issue():

    import random

    return random.choice(issue_data)

issue_closed = issue_data[0]
issue_with_body = issue_data[1]
issue_with_labels = issue_data[2]
issue_with_assignees = issue_data[3]
issue_empty = issue_data[4]