"""Add collection status enums

Revision ID: 18
Revises: 17
Create Date: 2023-04-20 13:50:35.963410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18'
down_revision = '17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection_status', 'core_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SUCCESS', 'PENDING', 'ERROR', 'COLLECTING', name='corestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"),
               schema='augur_operations')
    op.alter_column('collection_status', 'secondary_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SUCCESS', 'PENDING', 'ERROR', 'COLLECTING', name='secondarystatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"),
               schema='augur_operations')
    op.alter_column('collection_status', 'facade_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SUCCESS', 'PENDING', 'ERROR', 'COLLECTING', 'INITIALIZING', 'UPDATE', 'FAILED_CLONE', name='facadestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"),
               schema='augur_operations')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection_status', 'facade_status',
               existing_type=sa.Enum('SUCCESS', 'PENDING', 'ERROR', 'COLLECTING', 'INITIALIZING', 'UPDATE', 'FAILED_CLONE', name='facadestatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"),
               schema='augur_operations')
    op.alter_column('collection_status', 'secondary_status',
               existing_type=sa.Enum('SUCCESS', 'PENDING', 'ERROR', 'COLLECTING', name='secondarystatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"),
               schema='augur_operations')
    op.alter_column('collection_status', 'core_status',
               existing_type=sa.Enum('SUCCESS', 'PENDING', 'ERROR', 'COLLECTING', name='corestatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"),
               schema='augur_operations')
    # ### end Alembic commands ###
